config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  resources :projects
  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :delete_all
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    redirect_to project_path Project.last
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.name = "New Project"
    @project.save
    redirect_to @project
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { respond_with_bip(@project) }
      else
        format.html { render :edit }
        format.json { respond_with_bip(@project) }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    redirect_to task_path Task.last
  end

  def show
    redirect_to @task.project
  end

  def new
    @task = Task.new
    @task.name = 'New Task'
    @task.project_id = params[:project]
    @task.save
    redirect_to @task
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { respond_with_bip(@task) }
      else
        format.html { render :edit }
        format.json { respond_with_bip(@task) }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to @task.project
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :project)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bip(object, field, options={})
    random = Random.rand(999999999999)
    cls = bip_class(object, field)
    options[:id] = "#{cls}_#{random}"
    options[:class] = cls
    best_in_place object, field, options
  end

  def bip_class(object, field)
    "bestinplace_#{object.class}_#{object.id}_#{field}".downcase
  end

  def bip_span(object, field)
    content_tag(:span, object[field], class: bip_class(object, field))
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_auth_links.html.haml
- if user_signed_in?
  %li.btn.btn-outline-secondary= link_to "Profile", edit_user_registration_path
- else
  %li.btn.btn-outline-secondary= link_to "Sign Up", new_user_registration_path
  %li.divider{:role => "separator"} &nbsp;&nbsp;
  %li.btn.btn-outline-secondary= link_to "Login", new_user_session_path
- if user_signed_in?
  %li.divider{:role => "separator"} &nbsp;&nbsp;
  %li.btn.btn-outline-secondary= link_to "Logout", destroy_user_session_path, method: :delete

app/views/layouts/_nav.html.haml
%header
  %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    %a.navbar-brand{:href => "/"}
      = image_tag 'taskrepoicon.png', size: 30
      TaskRepo
    %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item.active
          %a.nav-link{:href => "/"}
            Projects
      %ul.nav.navbar-nav.ml-auto.w-100.justify-content-end
        = render 'layouts/auth_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title TaskRepo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/nav'
    -if notice
      %p.notice= notice
    -if alert
      %p.alert= alert
    %main.container= yield

app/views/projects/_detail.html.haml
.card.border-secondary.text-white.bg-transparent
  .card-header.border-secondary
    %h4.d-inline= bip @project, :name
  .card-body
    %span.bg-transparent.border-secondary
      = bip @project, :description, as: :textarea
  .card-footer.text-center
    = link_to 'Delete', @project, method: :delete, data: { confirm: "Are you sure you want to delete #{@project.name}?" }, class: 'd-inline btn btn-sm border-danger text-danger'

app/views/projects/_form.html.haml
= bootstrap_form_for project do |form|
  - if project.errors.any?
    #error_explanation
      %h2
        = pluralize(project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - project.errors.full_messages.each do |message|
          %li= message
  .field
    = form.text_field :name, id: :project_name
  .field
    = form.text_area :description, id: :project_description
  .actions
    = form.submit

app/views/projects/_project.html.haml
-if project == @project
  %a.list-group-item.bg-secondary.text-white.border-secondary.highlight{href: '#'}
    %strong= bip_span project, :name
-else
  %a.list-group-item.bg-transparent.border-secondary{href: project_path(project)}
    = bip_span project, :name

app/views/projects/_projects.html.haml
.card.border-secondary.text-white.bg-transparent
  .card-header.border-secondary
    %h4.d-inline Projects
    %a.btn.btn-sm.border-primary.float-right{href: new_project_path} + New Project
  .list-group.list-group-flush= render @projects

app/views/projects/_tasks.html.haml
.card.border-secondary.text-white.bg-transparent
  .card-header.border-secondary
    %h4.d-inline Tasks
    %a.btn.btn-sm.border-primary.float-right{href: new_task_path(project: @project)} + New Task
  .list-group.list-group-flush
    = render @project.tasks

app/views/projects/edit.html.haml
%h1 Editing Project
= render 'form', project: @project
= link_to 'Show', @project
|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
.row
  .col.col-sm-3
    = render 'projects'
  .col.col-sm-4
    %h1 Tasks
  .col.col-sm-5
    %h1 Details

app/views/projects/new.html.haml
%h1 New Project
= render 'form', project: @project
= link_to 'Back', projects_path

app/views/projects/show.html.haml
.row
  .col.col-sm-4= render 'projects', current_project: @project
  .col.col-sm-4
    = render 'tasks'
  .col.col-sm-4
    = render 'detail'

app/views/tasks/_task.html.haml
%li.list-group-item.bg-transparent.border-secondary.text-white
  = bip task, :name
  %a.d-inline.text-danger{href: task_path(task), data: { method: :delete, confirm: "Are you sure you want to delete #{task.name}?" }}
    %span.text-danger.float-right &times;